
:toc:               left
:toc-title:         Connector Summary
:toclevels:         2
:last-update-label!:
:docinfo:
:source-highlighter: coderay
:icons: font


= API Fortress Connector API Reference

+++
The API Fortress connector allows you to send API payloads to API Fortress for testing
+++

*Additional Info*
[width="50", cols=".<60%,^40%" ]
|======================
| Requires Mule Enterprise License |  Yes icon:star[]  {nbsp}
| Requires Entitlement |  No icon:remove[]  {nbsp}
| Mule Version | 3.8.0 or higher
|======================


== Configs
---
=== Configuration
`<api-fortress:config>`



`Configuration` 
+++
The global configuration
+++


==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
| Name | Java Type | Description | Default Value | Required
|name | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | The name of this configuration. With this name can be later referenced. | | *x*{nbsp}
| totalConnections | +++int+++ | +++Max number of simultaneous connections+++ |  2 | {nbsp}
| connectTimeout | +++int+++ | +++Timeout during connection in seconds+++ |  5 | {nbsp}
| socketTimeout | +++int+++ | +++Socket timeout in seconds+++ |  30 | {nbsp}
| threshold | +++int+++ | +++The threshold multiplier. The connector counts the test requests and accepts them only when the counter
is a multiple of this value. This is done to relax the sampling rate+++ |  1 | {nbsp}
| silent | +++boolean+++ | +++When set to true, no notification will be triggered+++ |  false | {nbsp}
| dryRun | +++boolean+++ | +++When set to true, events won't be saved in API Fortress+++ |  false | {nbsp}
|======================



== Processors

---

=== Single test synchronous
`<api-fortress:single-test-synchronous>`




+++
Runs a single test in a synchronous flavor. The connector will wait for the result of the test and set it as payload
+++


    
                    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
payload icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>+++ | +++The payload, either in the form of string or object. The valid string formats are JSON, XML or plain text. The object can be anything that can be converted into a JSON+++ | #[payload] | {nbsp}




| 
hook  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The API Hook URL. You can retrieve this in your API Fortress company account+++ |  | *x*{nbsp}




| 
testId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The test id. It can be found in the test interstitial page, on the API Fortress dashboard+++ |  | *x*{nbsp}




| 
headers  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++The response headers of the payload it's being tested. 'content-type' is the only mandatory header+++ | #[message.inboundProperties] | {nbsp}




| 
variables  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Extra variables to be injected in the scope of the test. Ie. server name, flow name, geographic location, local time+++ |  | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="javadocs/org/mule/modules/apifortress/responses/TestExecutionResponse.html">TestExecutionResponse</a>+++ | +++A TestExecutionResponse object, containing the test result information, such as failures count, warnings count and critical failures+++
|======================




---

=== Single test passthrough
`<api-fortress:single-test-passthrough>`




+++
Runs a single test in an asynchronous flavor. The input payload will be put back in the flow untouched once the operation is done,
so that further actions can be done on it by the rest of the flow.
+++


    
                    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
payload icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>+++ | +++The payload, either in the form of string or object. The valid string formats are JSON, XML or plain text. The object can be anything that can be converted into a JSON+++ | #[payload] | {nbsp}




| 
hook  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The API Hook URL. You can retrieve this in your API Fortress company account+++ |  | *x*{nbsp}




| 
testId  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The test id. It can be found in the test interstitial page, on the API Fortress dashboard+++ |  | *x*{nbsp}




| 
headers  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++The response headers of the payload it's being tested. 'content-type' is the only mandatory header+++ | #[message.inboundProperties] | {nbsp}




| 
variables  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Extra variables to be injected in the scope of the test. Ie. server name, flow name, geographic location, local time+++ |  | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>+++ | +++The original payload passed to this operation+++
|======================




---

=== Automatch synchronous
`<api-fortress:automatch-synchronous>`




+++
Runs an automatch testing suite in a synchronous way. The connector will wait for the test results from the API Fortress service and return
it in the flow as payload.
The automatch system will determine which tests need to run based on the automatch pattern.
+++


    
                    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
payload icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>+++ | +++The payload, either in the form of string or object. The valid string formats are JSON, XML or plain text. The object can be anything that can be converted into a JSON+++ | #[payload] | {nbsp}




| 
hook  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The API Hook URL. You can retrieve this in your API Fortress company account+++ |  | *x*{nbsp}




| 
automatch  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++An automatch pattern is a slash separated string, using "*" as wildcard, that describes the endpoint being tested. It will allow the API Fortress system to determine which tests need to run.+++ |  | *x*{nbsp}




| 
headers  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++The response headers of the payload it's being tested. 'content-type' is the only mandatory header+++ | #[message.inboundProperties] | {nbsp}




| 
variables  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Extra variables to be injected in the scope of the test. Ie. server name, flow name, geographic location, local time+++ |  | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="javadocs/org/mule/modules/apifortress/responses/TestExecutionResponses.html">TestExecutionResponses</a>+++ | +++A TestExecutionResponses object, a collection representing all the test execution results for this automatch operation+++
|======================


==== APIDoc Reference
+++http://apifortress.com/doc/automatch/+++


---

=== Automatch passthrough
`<api-fortress:automatch-passthrough>`




+++
Runs an automatch testing suite in an asynchronous way. the API Fortress service will not return the tests result and run them in background.
The connector will leave the payload untouched for further operations.
The automatch system will determine which tests need to run based on the automatch pattern.
+++


    
                    
==== Attributes
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|======================
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}



| 
payload icon:envelope[] | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>+++ | +++The payload, either in the form of string or object. The valid string formats are JSON, XML or plain text. The object can be anything that can be converted into a JSON+++ | #[payload] | {nbsp}




| 
hook  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++The API Hook URL. You can retrieve this in your API Fortress company account+++ |  | *x*{nbsp}




| 
automatch  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>+++ | +++An automatch pattern is a slash separated string, using "*" as wildcard, that describes the endpoint being tested. It will allow the API Fortress system to determine which tests need to run+++ |  | *x*{nbsp}




| 
headers  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++The response headers of the payload it's being tested. 'content-type' is the only mandatory header+++ | #[message.inboundProperties] | {nbsp}




| 
variables  | +++<a href="http://docs.oracle.com/javase/7/docs/api/java/util/Map.html">Map</a><<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/String.html">String</a>,<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>>+++ | +++Extra variables to be injected in the scope of the test. Ie. server name, flow name, geographic location, local time+++ |  | {nbsp}


|======================

==== Returns
[cols=".^40%,.^60%", options="header"]
|======================
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html">Object</a>+++ | +++The original payload passed to this operation+++
|======================


==== APIDoc Reference
+++http://apifortress.com/doc/automatch/+++












