= API Fortress Anypoint Connector
:keywords: api, apifortress, testing
:imagesdir: ./_images
:toc: macro
:toclevels: 2


toc::[]


== Introduction

API Fortress is a world leader in API testing. The API Fortress Anypoint connector allows you to serialize your API responses in Mule and send them to API Fortress
for testing. Based on the configuration, the results of the tests can be sent back to the Mule flow or be stored in API Fortress for further analysis.

Read through this user guide to understand how to set up and configure a basic flow using the connector.

MuleSoft maintains this connector under the link:https://docs.mulesoft.com/mule-user-guide/v/3.8/anypoint-connectors#connector-categories[MuleSoft Certified] support policy.


== Prerequisites

This document assumes that you are familiar with Mule,
link:https://docs.mulesoft.com/mule-user-guide/v/3.8/anypoint-connectors[Anypoint Connectors], and
link:https://docs.mulesoft.com/mule-fundamentals/v/3.8/anypoint-studio-essentials[Anypoint Studio Essentials]. To increase your familiarity with Studio, consider completing a link:https://docs.mulesoft.com/mule-fundamentals/v/3.8/basic-studio-tutorial[Anypoint Studio Tutorial]. This page requires some basic knowledge of link:/mule-fundamentals/v/3.8/mule-concepts[Mule Concepts], link:/mule-fundamentals/v/3.8/elements-in-a-mule-flow[Elements in a Mule Flow], and link:/mule-fundamentals/v/3.8/global-elements[Global Elements].


[[requirements]]
=== Hardware and Software Requirements

For hardware and software requirements, please visit the link:https://docs.mulesoft.com/mule-user-guide/v/3.8/hardware-and-software-requirements[Hardware and Software Requirements] page.



=== Compatibility

*Versions* +
Mule 3.8.0 or newer

== Installing the Connector

You can install the connector in Anypoint Studio using the instructions in
link:https://docs.mulesoft.com/mule-fundamentals/v/3.8/anypoint-exchange#installing-a-connector-from-anypoint-exchange[Installing a Connector from Anypoint Exchange].

=== Upgrading from an Older Version

If you’re currently using an older version of the connector, a small popup appears in the bottom right corner of Anypoint Studio with an "Updates Available" message.

. Click the popup and check for available updates. 
. Click the Connector version checkbox and click *Next* and follow the instructions provided by the user interface. 
. *Restart* Studio when prompted. 
. After restarting, when creating a flow and using the connector, if you have several versions of the connector installed, you may be asked which version you would like to use. Choose the version you would like to use.

Additionally, we recommend that you keep Studio up to date with its latest version.

== Configuring the Connector Global Element

To use the API Fortress connector in your Mule application, you must configure a global API Fortress element that can be used by the API Fortress connector (read more about  link:https://docs.mulesoft.com/mule-fundamentals/v/3.8/global-elements[Global Elements]). The API Fortress connector offers the following global configuration:
[width="100a",cols="50a,50a",options="header",]
|===
|Field |Description
|*connectTimeout* | Timeout to connect in seconds.
|*socketTimeout* | Socket timeout in seconds.
|*totalConnections* | Maximum number of parallel HTTP connections.
|*threshold* | Run a test after a certain number of requests have been received.
|*silent* | True if the API Fortress cloud shouldn't send failure notifications.
|*dryRun* | True if the API Fortress cloud shouldn't store test results.


|===

== Using the Connector

The connector can be placed anywhere in a Mule flow. The payload can either be a plain JSON/XML string or a POJO object that will be converted in JSON.
Other than the payload, connector will require access to the response headers you can configure in the connector instance configuration. The "content-type" header should be
present, otherwise text/plain will be used.

Here's the operations the connector provides.

[width="100a",cols="20a,30a,50a",options="header",]
|===
|Field |Description| Parameters
|*singleTestSynchronous* | The test will run return the results of the test | hook,testId,headers,variables.
|*singleTestPassthrough* | The test will run and return the received payload | hook,testId,headers,variables.
|*automatchSynchronous* | The test will run and return tthe results of the test, the "automatch" variable will be used to determine which tests to run | hook,headers,variables.
|*automatchTestPassthrough* | The test will run and return the received payload, the "automatch" variable will be used to determine which tests to run | hook,testId,headers,variables.

|===

The Parameters are:
[width="100a",cols="20a,80a",options="header",]
|===
|Parameter | Description
|*hook* | the hook URL. You can create hook urls in the API Fortress company dashboard
|*testId* | for single test run, the ID of the test to run
|*automatch* | for automatch operations, a path that identifies the URL of the endpoint 
|*headers* | a map representing the received headers. Typically represented by inboundProperties
|*variables* | extra variables to be injected in the scope of the test

|=== 

=== Connector Namespace and Schema

When designing your application in Studio, the act of dragging the connector from the palette onto the Anypoint Studio canvas should automatically populate the XML code with the connector *namespace* and *schema location*.

*Namespace:* `http://www.mulesoft.org/schema/mule/connector`
*Schema Location:* `http://www.mulesoft.org/schema/mule/connector/current/mule-connector.xsd`

[TIP]
If you are manually coding the Mule application in Studio's XML editor or other text editor, define the namespace and schema location in the header of your *Configuration XML*, inside the `<mule>` tag.

[source, xml,linenums]
----
<mule xmlns="http://www.mulesoft.org/schema/mule/core"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:connector="http://www.mulesoft.org/schema/mule/connector"
      xsi:schemaLocation="
               http://www.mulesoft.org/schema/mule/core
               http://www.mulesoft.org/schema/mule/core/current/mule.xsd
               http://www.mulesoft.org/schema/mule/connector
               http://www.mulesoft.org/schema/mule/connector/current/mule-connector.xsd">

      <!-- put your global configuration elements and flows here -->

</mule>
----


=== Using the Connector in a Mavenized Mule App

If you are coding a Mavenized Mule application, this XML snippet must be included in your `pom.xml` file.

[source,xml,linenums]
----
<dependency>
   <groupId>org.mule.modules</groupId>
   <artifactId>api-fortress-connector</artifactId>
   <version>1.0.0-RELEASE</version>
</dependency>
----

[TIP]
====
Inside the `<version>` tags, put the desired version number, the word `RELEASE` for the latest release, or `SNAPSHOT` for the latest available version. The available versions to date are:

* *1.0.0-RELEASE*
====


== Demo Mule Applications Using Connector
////
add links to demos
////


=== Simple Passthrough Use Case
The simplest use case is the validation of a response coming from an endpoint.


. Set up a basic HTTP entry point

. Deploy an HTTP request to an endpoint of your choice

. Deploy the API Fortress connector and create a default global configuration, setting silent=true

. Select the "Single test passthrough" operation

. In your API Fortress account, in the company dashboard, create an API Hook URL for your project. Use it as the "hook" parameter

. In your API Fortress account, in the test details page, obtain a test ID. Use it as the "testId" parameter

. Run the flow and hit the entry point

. In the API Fortress dashboard, verify the result of the test 

=== Simple Passthrough Use Case - XML

Paste this into Anypoint Studio to interact with the example use case application discussed in this guide.

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns:http="http://www.mulesoft.org/schema/mule/http" xmlns:api-fortress="http://www.mulesoft.org/schema/mule/api-fortress" xmlns="http://www.mulesoft.org/schema/mule/core" xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
	xmlns:spring="http://www.springframework.org/schema/beans" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd
http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
http://www.mulesoft.org/schema/mule/api-fortress http://www.mulesoft.org/schema/mule/api-fortress/current/mule-api-fortress.xsd">
    <http:listener-config name="HTTP_Listener_Configuration" host="0.0.0.0" port="8081" doc:name="HTTP Listener Configuration"/>
    <http:request-config name="HTTP_Request_Configuration" protocol="HTTPS" host="mastiff.apifortress.com" port="443" basePath="/api/examples/retail" doc:name="HTTP Request Configuration"/>
    <api-fortress:config name="API_Fortress__Configuration" silent="true" dryRun="true" doc:name="API Fortress: Configuration"/>
    <flow name="muleexampleFlow">
        <http:listener config-ref="HTTP_Listener_Configuration" path="/test" doc:name="HTTP"/>
        <http:request config-ref="HTTP_Request_Configuration" path="/products" method="GET" doc:name="HTTP"/>
        <api-fortress:single-test-synchronous config-ref="API_Fortress__Configuration" hook="https://mastiff.apifortress.com/app/api/rest/v3/9e05babb-e332-4715-bba5-a1a487a4b05c324" testId="57ce873ebbb0fb02e8069d42" doc:name="API Fortress"/>
    </flow>
</mule>

----

* Access the link:https://docs.mulesoft.com/release-notes/api-fortress-connector-release-notes[API Fortress Connector Release Notes].
